### ISSUE TITLE
the value 0.08 & 0.05

### ISSUE THREAD

**Issue by joker594302831** [MisterY52/apex_dma_kvm_pub#12]
https://github.com/MisterY52/apex_dma_kvm_pub/blob/3a4e7716487756771acc2d1e88258ed186e8f6a9/apex_dma/Game.cpp#L267
Why there are 0.08 and 0.05 correction data, what is the role of respectively, I want to know the principle, some weapons are not allowed to be far away, may be flying overhead, how to correct it

**Comment by MisterY52** [comment]
The correction was made to compensate a bit the aim with default smooth. It isn't really necessary however.
