### ISSUE TITLE
calrification please

### ISSUE THREAD

**Issue by aDioS786** [MisterY52/apex_dma_kvm_pub#13]
Hi,
Not an issue but wanted to get some clarification. Can you please tell me what is the difference some of the attributes/offsets below ?

-      #define OFFSET_ORIGIN				0x14c //m_vecAbsOrigin (**This is vec 3 player location coordinates**)
-     #define OFFSET_VIEWANGLES			0x252c - 0x14 //m_ammoPoolCapacity - 0x14 (**vec 2 mouse x,y axis**)

What's the difference between bottom three please.

-     #define OFFSET_CAMERAPOS			0x1ED0
-     #define OFFSET_AIMPUNCH			0x2430 //m_currentFrameLocalPlayer.m_vecPunchWeapon_Angle
-     #define OFFSET_BREATH_ANGLES		OFFSET_VIEWANGLES - 0x10

Thanks

**Comment by Bix3** [comment]
offset_origin is the offset for the position of the player.
offset_viewangles is the offset for the rotation(the angles you modify for aimbot).
offset camerapos is the offset to the camera position(needed for aimbot).
offset aimpunch is the punchangles, this is recoilangles (its the angle that the recoil made your gun move from its supposed position).
breath angles is the same as punch angles for breath

**Comment by aDioS786** [comment]
thanks for ur response. The offset_viewangles, believe these are player feet? and cameraPost would be at players head?
What Breath angles would be used for, as still not clear on that one.

Lastly, what be the best approach to reduce recoil, not sure if writing to viewangles is highly risky / detectable or there is another good way to do it?

Thanks again

**Comment by Bix3** [comment]
viewangles is the rotation, camerapos is the position of the camera, should be close to head usually but not the same as head, for reduce recoil just calculate the punchangles into your calculations for aimbot then the aimbot will account for recoil same for breath angles. breath angles is for example in sniper the slow shaking
