### ISSUE TITLE
Offset problem

### ISSUE THREAD

**Issue by OkabeRintarou1** [MisterY52/apex_dma_kvm_pub#17]
I'm sorry to bother you. I have some questions.How do I get the offset of OFFSET_VISIBLE_TIME and OFFSET_AIMPUNCH.I found the offset code on GitHub, but it doesn't seem to provide these two items.Can you tell me how to do it? Thank you very much

**Comment by MisterY52** [comment]
You can find the offsets by using this offset dumper for example: https://github.com/CasualX/apexbot/tree/master/offsets
Search "CPlayer!lastVisibleTime" for OFFSET_VISIBLE_TIME and "m_currentFrameLocalPlayer.m_vecPunchWeapon_Angle" for OFFSET_AIMPUNCH.
