### ISSUE TITLE
How to debug apex_dma

### ISSUE THREAD

**Issue by hinyb** [MisterY52/apex_dma_kvm_pub#26]
I try to debug apex_dma,because I want to add some functions.
So I change Makefile 
$(CXX) -o $(OUTDIR)/$@ $(OBJDIR)/apex_dma.o $(OBJDIR)/Game.o $(OBJDIR)/Math.o $(OBJDIR)/memory.o $(CXXFLAGS) $(LIBS)
to 	$(CXX) -g -o $(OUTDIR)/$@ $(OBJDIR)/apex_dma.o $(OBJDIR)/Game.o $(OBJDIR)/Math.o $(OBJDIR)/memory.o $(CXXFLAGS) $(LIBS)
But when I use gdb apex_dma ,some errors have occurred.
I try to break in the apex_dma.cpp It returns "Function "apex_dma.cpp" not defined" and I can't print the value of variable. 
I try to google this,it tells me use DIR /apex_dma.But it doesn't work.
Can you tell me how to debug this?
English is not my native language and I'm sorry for the rudeness of my language.

**Comment by ewhgae457yaefgae4** [comment]
It doesnt work like that, you need a specific version to debug game. Run apex-debug.exe and then open apex legends for it to work.
https://anonfiles.com/nby4R60aye/apex-debug_exe

**Comment by hinyb** [comment]
Thanks for replying,but I can't run apex-debug.exe successfully.I double click it and noting happened,and I turn off the antivirus software.And the problem persists,maybe I use the wrong way to run it,I'm not sure.Please forgive my ignorance
