### ISSUE TITLE
"Initialization error: -1" When try to start apex_dma as root

### ISSUE THREAD

**Issue by daeeros** [MisterY52/apex_dma_kvm_pub#3]
https://sun6-22.userapi.com/dQ61seeQZnjtSTDmioYzMtWE3otguwRbsbLpZg/uXfsFCjzPfo.jpg

How can if fix it? Its mayby becose i using ubuntu integritry in windows from micrasoft store?

**Comment by MisterY52** [comment]
It doesn't work with WSL. You need to run Windows in a QEMU KVM.
