### ISSUE TITLE
any tutorial on using this?

### ISSUE THREAD

**Issue by johnpythonjohn3** [MisterY52/apex_dma_kvm_pub#8]
Seems it is actively updating. 

Someone told me the driver of DIRECT EFI is detected.

Looking for usable driver and hack code

**Comment by MurphyKyle** [comment]
That's correct, the way people have been using the EFI driver is too lazy to get by the AC now.

Look in the README for the main thread where usage instructions and other troubleshooting tips exist.

Another option would be looking into using the still working and undetected driver method: https://github.com/TheCruZ/kdmapper
