### ISSUE TITLE
Hi i got into error while building  in guest what to do to solve this :0

### ISSUE THREAD

**Issue by fazim-developer** [MisterY52/apex_dma_kvm_pub#9]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory	Client	C:\Users\shahe\Desktop\apex_dma_kvm_pub-master\apex_guest\Client\Client\overlay.h	20	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C28251	Inconsistent annotation for 'WinMain': this instance has no annotations. See c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\winbase.h(1006). 	Overlay	C:\Users\shahe\Desktop\apex_dma_kvm_pub-master\apex_guest\Overlay\Overlay\main.cpp	9

**Comment by MisterY52** [comment]
> Severity Code Description Project File Line Suppression State
> Error C1083 Cannot open include file: 'd3dx9.h': No such file or directory Client C:\Users\shahe\Desktop\apex_dma_kvm_pub-master\apex_guest\Client\Client\overlay.h 20
Install directx sdk: https://www.microsoft.com/en-us/download/details.aspx?id=6812

> Severity Code Description Project File Line Suppression State
> Warning C28251 Inconsistent annotation for 'WinMain': this instance has no annotations. See c:\program files (x86)\windows kits\10\include\10.0.19041.0\um\winbase.h(1006). Overlay C:\Users\shahe\Desktop\apex_dma_kvm_pub-master\apex_guest\Overlay\Overlay\main.cpp 9
This warning can be ignored.
